### PR TITLE
My-portfolio2

### PR DESCRIPTION
**Pull request by fauziyahzeeyah**
-  Add an icon to the title bar
-  Add keyframes and transition to CSS
-  Created a new popup.js files
-  Created a new Index.Html files
-  Updated my Readme.md and License
-  Deployed my code.

### CODE REVIEW

**Comment by fauziyahzeeyah** [comment]
### New changes made

-  Add new styles to the h1 tag
-  Update popup window

**Comment by bellom** [comment]
@fauziyahzeeyah,

### This is a manual review

You do not have all the changes in file changes on this PR, so, I can't use inline commit, all I can see is a variable name change you did.

# Request Changes 

There is no close button for the pop-up, see the screenshot below;

Keep in mind, for mobile, we should be able to see the close button on 375 px and above.

image

Cheers and Happy coding!

**Comment by fauziyahzeeyah** [comment]
https://github.com/fauziyahzeeyah/My-Portfolio2/pull/1 I have made the
changes required

**Comment by bellom** [comment]
@fauziyahzeeyah,

### This is a manual review

# Approved

Cheers and Happy coding!

**Comment by bellom** [comment]
@fauziyahzeeyah - Kindly check your email.

**Pull request merged**
